services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
  postgres-sql:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend:
    image: oven/bun
    restart: always
    volumes:
      - type: bind
        source: ./frontend
        target: /home/bun/app
    working_dir: /home/bun/app
    command: bun run dev
    ports:
      - 3000:3000
    environment:
      POSTGRES_URL: postgres://postgres:admin@postgres-sql:5432/postgres

  jsreport:
    image: jsreport/jsreport:latest
    container_name: jsreport
    ports:
      - "5488:5488"
    environment:
      - JSREPORT_ADMIN_PASSWORD=admin
      - JSREPORT_ENABLE_XSRF=false
    volumes:
      - /jsreport/data